name: hello world
on: 
  push:
    branches: 
      - main
    paths-ignore: [.github/**]
  
  workflow_dispatch:
    
jobs:
  my-first-job:
    runs-on: ubuntu-latest
    
    steps: 
      - run: echo "hello world"
