name: hello world
on: 
  push:
    branches: 
      - main
    paths-ignore: [.github/**]
  
  workflow_dispatch:
    
jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - run: |
          echo "🎉 The job was triggered by event: ${{ github.event_name }}"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
        
      - shell: bash
        run: |
           echo MY_ENV_VAR="HELLO WOLRD" >> $GITHUB_ENV
           
      - id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT
        
      - id: step2
        run: echo "test=world" >> $GITHUB_OUTPUT
          
  Show-env:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
  
